"""baseline

Revision ID: 46e791ab5190
Revises: 
Create Date: 2026-07-15 19:56:35.886980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e791ab5190'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao_cronograma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horas_por_dia', sa.Float(), nullable=False),
    sa.Column('materias_fracas_json', sa.JSON(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_caderno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('materia', sa.String(), nullable=False),
    sa.Column('anotacao', sa.Text(), nullable=False),
    sa.Column('questao_json', sa.JSON(), nullable=True),
    sa.Column('enunciado', sa.Text(), nullable=True),
    sa.Column('resposta_dada', sa.String(), nullable=True),
    sa.Column('pergunta', sa.Text(), nullable=True),
    sa.Column('resposta', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_caderno_dedup_simulado', 'itens_caderno', ['enunciado'], unique=True, sqlite_where=sa.text("origem = 'simulado'"))
    op.create_table('perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('data_prova', sa.Date(), nullable=True),
    sa.Column('ultima_conversa_json', sa.JSON(), nullable=True),
    sa.Column('ultima_conversa_atualizada_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plano_cronograma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gerado_em', sa.DateTime(), nullable=False),
    sa.Column('data_prova', sa.Date(), nullable=True),
    sa.Column('horas_por_dia', sa.Float(), nullable=False),
    sa.Column('dias_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', name='uq_atividade_data')
    )
    op.create_table('resultados_simulado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('modo', sa.String(), nullable=False),
    sa.Column('materia_filtro', sa.String(), nullable=True),
    sa.Column('acertos', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('duracao_segundos', sa.Integer(), nullable=False),
    sa.Column('questoes_json', sa.JSON(), nullable=False),
    sa.Column('respostas_json', sa.JSON(), nullable=False),
    sa.Column('por_materia_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultados_simulado')
    op.drop_table('registro_atividade')
    op.drop_table('plano_cronograma')
    op.drop_table('perfil')
    op.drop_index('ix_caderno_dedup_simulado', table_name='itens_caderno', sqlite_where=sa.text("origem = 'simulado'"))
    op.drop_table('itens_caderno')
    op.drop_table('configuracao_cronograma')
    # ### end Alembic commands ###
